### ISSUE TITLE
Scanner Callback Persists Across Screens

### ISSUE THREAD

**Issue by muhammadarslan1998** [luis901101/blue_bird_scanner#2]
Problem description: When navigating between screens that implement ScannerCallBack, the callback does not reset correctly upon navigating back. Specifically:

The scannerCallBack remains attached to the previous screen’s instance even after popping back, causing the onDecoded method of the latest screen to continue receiving callbacks instead of the currently active screen.
Expected behavior: When navigating to a new screen that sets scannerCallBack and then navigating back, the scannerCallBack should reset to the currently active screen’s callback.

Steps to reproduce:

Implement ScannerCallBack in two different screens.
Set scannerCallBack to each screen’s callback in their respective initState.
Navigate from the first screen to the second screen.
Observe that upon returning to the first screen, the scannerCallBack still invokes the second screen’s onDecoded method, rather than the first screen's.

**Comment by luis901101** [comment]
That’s correct the `scannerCallBack` is single instance. Note that you have to `set` the callback and also the plugin doesn’t know about navigation. To make it work as you expect you just have to re-set the callBack when retuning from your second screen. Lets say something like:

```dart
Navigator.push(context, SecondRoute()).whenComplete(() => scanner.scannerCallBack = this);
```

**Comment by muhammadarslan1998** [comment]
> That’s correct the `scannerCallBack` is single instance. Note that you have to `set` the callback and also the plugin doesn’t know about navigation. To make it work as you expect you just have to re-set the callBack when retuning from your second screen. Lets say something like:
> 
> ```dart
> Navigator.push(context, SecondRoute()).whenComplete(() => scanner.scannerCallBack = this);
> ```

i have tried this already but did not work

**Comment by luis901101** [comment]
> > That’s correct the `scannerCallBack` is single instance. Note that you have to `set` the callback and also the plugin doesn’t know about navigation. To make it work as you expect you just have to re-set the callBack when retuning from your second screen. Lets say something like:
> > ```dart
> > Navigator.push(context, SecondRoute()).whenComplete(() => scanner.scannerCallBack = this);
> > ```
> 
> i have tried this already but did not work

It should work, debug step by step to check where it could be failing, put a break point in the plugin's callback setter to see who is setting the callback the last.
Regarding the plugin's code it's really simple, you can check it here:
https://github.com/luis901101/blue_bird_scanner/blob/4f6ba3fe57cd24c9431fb7ed6f3eedda54e332ac/lib/blue_bird_scanner.dart#L9-L92

Note how the `_scannerCallBack` is a single variable in the plugin's class and the `onDecoded(...)` and `onError(...)` will be called through the callback.

**Comment by muhammadarslan1998** [comment]
this is my code for first screen `final blueBirdScanner = BlueBirdScan;
Timer? scannerDelay;


  @override
  void initState() {
    blueBirdScanner.startScanner();
    blueBirdScanner.scannerCallBack = this;    super.initState();
  }
  
   @override
  void onDecoded(String? result) {
    print("ScannedCode$result");
    FocusScope.of(context).unfocus();
    scannerDelay?.cancel();
    scannerDelay = Timer(const Duration(milliseconds: 300), () {
              palletController.text = result.toString();
        _scannedCode = result;
        previousScannedCode = _scannedCode;
        Get.find<DispatchLogic>().scanController.text = dropDownValue != null ? _scannedCode.toString() : "";
   
      createList();
    });
  }
  
  and this is my navigator code 
  
    Navigator.push(context, MaterialPageRoute(builder: (context)=>ChangePallet(  ))).whenComplete(() => blueBirdScanner.scannerCallBack = this);
`

this is my second screen code 
`
  final blueBirdScanner = BlueBirdScanner();
  Timer? scannerDelay;
  
  
    @override
  void initState() {
    blueBirdScanner.startScanner();
    blueBirdScanner.scannerCallBack = this;
    super.initState();
  }
  
    @override
  void onDecoded(String? result) {
    print("RESULT$result");
    if(mounted){
    scannerDelay?.cancel();
    scannerDelay = Timer(const Duration(milliseconds: 300), () {

        _scannedCode = result;
        _previousscannedCode = _scannedCode;
        // newPalletController.text = _scannedCode.toString();
        setState(() {});
      checkChangePallet();
    });
}
  }

  @override
  void dispose() {
    blueBirdScanner.stopScanner();
    scannerDelay?.cancel();
    super.dispose();
  }

`

i am printing the values both on second screen and first screen when i navigate back to first screen it still prints the value from the second screen which is like "RESULTRrSi1g3Pf9" instead of first which means it still is triggering the second screen onDecoded method

**Comment by luis901101** [comment]
You have a `blueBirdScanner.stopScanner();` in the `dispose()` of SecondScreen, if you stop the scanner then it will be stopped in the FirstScreen... 
If you will always return to FirstScreen from SecondScreen then don't `stopScanner()` on SecondScreen `dispose()`, otherwise you will have to also `startScanner()` when returning from SecondScreen

The thing is everything with the Scanner is single instance _(ignore the fact that you create an instance of the plugin on each screen, treat the plugin as singleton instance... this is something I maybe update in the feature to make the Plugin singleton to avoid confusion)_... all you do to the scanner will be applied globally... so you have to take into account the states on each screen you use the scanner.

**Comment by muhammadarslan1998** [comment]
Thank you i have resolved the issue by this `.whenComplete((){
                                          blueBirdScanner=BlueBirdScanner();
                                          blueBirdScanner.startScanner();
                                          blueBirdScanner.scannerCallBack = this;
                                        } );`
